### PR TITLE
Enable proxy

### PR DESCRIPTION
**Pull request by tibeer**
This change adds a squid proxy that allows only whitelisted traffic to every component, that is set to use this proxy.

partly #1439 

Signed-off-by: Tim Beermann <beermann@osism.tech>

### CODE REVIEW

**Comment by tibeer** [comment]
Do not merge! This would break the testbed as the mirrors are not prepared yet.

**Comment by osfrickler** [comment]
> Do not merge! This would break the testbed as the mirrors are not prepared yet.

Better set the PR to "Draft" status then instead of using the "DNM" tag.

**Comment by tibeer** [comment]
Needs to wait until
https://github.com/osism/ansible-collection-commons/pull/451
and
https://github.com/osism/ansible-collection-services/pull/960
have been merged

**Review by matfechner — APPROVED** [review]
LGTM

**Review by berendt — CHANGES_REQUESTED** [review]
Blockig for the moment.

**Comment by tibeer** [comment]
@berendt this should now be ready to be merged.

**Review by berendt — APPROVED** [review]

**Pull request merged**
