### PR TITLE
Introduce Opentofu, replace Terraform by Opentofu

### PR DESCRIPTION
**Pull request by scoopex**
This change depends on https://github.com/osism/testbed/pull/1879

The follwing documentation change includes also changes for this PR: https://github.com/osism/osism.github.io/pull/280

### CODE REVIEW

**Comment by berendt** [comment]
Also depends on a stable Opentofu release (https://github.com/opentofu/opentofu/releases/tag/v1.6.0-beta2). beta2 is out now. I think the first stable release will be there before Christmas break.

**Comment by scoopex** [comment]
> Also depends on a stable Opentofu release (https://github.com/opentofu/opentofu/releases/tag/v1.6.0-beta2). beta2 is out now. I think the first stable release will be there before Christmas break.

I updated the PR to v1.6.0-beta2

**Comment by berendt** [comment]
GA @ early Januar 2024 (10th)

**Comment by berendt** [comment]
@scoopex Please rebase on main. There are a lot of merge conflicts at the moment because this PR includes commits that are already merged.

**Comment by berendt** [comment]
Existing .terraform directory + lock file in terraform has to be deleted because of:

```
Error: Inconsistent dependency lock file

The following dependency selections recorded in the lock file are inconsistent with the current
configuration:
  - provider registry.opentofu.org/hashicorp/local: required by this configuration but no version is selected
  - provider registry.opentofu.org/hashicorp/null: required by this configuration but no version is selected
  - provider registry.opentofu.org/terraform-provider-openstack/openstack: required by this configuration but no version is selected

To update the locked dependency selections to match a changed configuration, run:
  tofu init -upgrade
```

**Comment by scoopex** [comment]
> Existing .terraform directory + lock file in terraform has to be deleted because of:
> 
> ```
> Error: Inconsistent dependency lock file
> 
> The following dependency selections recorded in the lock file are inconsistent with the current
> configuration:
>   - provider registry.opentofu.org/hashicorp/local: required by this configuration but no version is selected
>   - provider registry.opentofu.org/hashicorp/null: required by this configuration but no version is selected
>   - provider registry.opentofu.org/terraform-provider-openstack/openstack: required by this configuration but no version is selected
> 
> To update the locked dependency selections to match a changed configuration, run:
>   tofu init -upgrade
> ```

The directory is now wiped with "make clean".

https://github.com/osism/testbed/pull/1881/commits/f74b55780300e3bb9130a5c61a3451de1daf49c1

**Comment by berendt** [comment]
Tested latest state. Works for me. Will run one more test tomorrow.

**Pull request merged**
