### PR TITLE
removed unused tf vars

### PR DESCRIPTION
**Pull request by frosty-geek**
ref: #1468

Signed-off-by: Ralf Heiringhoff <frosty-geek@users.noreply.github.com>

### CODE REVIEW

**Comment by berendt** [comment]
Keep network_availability_zone, this is used in an overlay and is required.

**Comment by berendt** [comment]
Parameters also have to be removed from the table of parameters in doc/source/configuration.rst.

**Comment by frosty-geek** [comment]
I'll add the changes later today

**Comment by berendt** [comment]
Let's merge this as-is and cleanup the table of parameter with the migration to Docusaurus.

**Pull request merged**
