### PR TITLE
Simplify the deployment of the identity services

### PR DESCRIPTION
**Pull request by berendt**
Signed-off-by: Christian Berendt <berendt@osism.tech>

### CODE REVIEW

**Review by osfrickler — APPROVED** [review]

**Comment by osfrickler** [comment]
recheck

**Comment by osfrickler** [comment]
ceph failure on upgrade was likely unrelated

**Comment by osfrickler** [comment]
upgrade timeout still looks unrelated. do we want to add a job testing the identity-only scenario though? would be better to safeguard against regressions IMO. could be done as a follow-up.

**Comment by berendt** [comment]
> upgrade timeout still looks unrelated. do we want to add a job testing the identity-only scenario though? would be better to safeguard against regressions IMO. could be done as a follow-up.

https://github.com/osism/testbed/issues/1424

**Pull request merged**
