### PR TITLE
Install IdP discovery authenticator

### PR DESCRIPTION
**Pull request by JuanPTM**
Follow up on [#314](https://github.com/SovereignCloudStack/issues/issues/314)

### CODE REVIEW

**Comment by berendt** [comment]
Is it not a better idea to add this to the Keycloak image itself? For a testbed it's probably fine to download random archives from the internet. I think this will not be possible in productive environments.

**Comment by JuanPTM** [comment]
I'm fine with that too, but who were will be the custom keycloak container be stored and who will be in charge on keep it updated ?

**Comment by berendt** [comment]
You can provide the image in a process as it is best for you. Probably the best way to do this is to create e.g. SovereignCloudStack/container-image-keycloak repository and then upload the image to the Harbor from the SCS project. Then the image is in a central place of the project and you can maintain it there in the future.

**Comment by garloff** [comment]
The build process needs to be automated, so we can always update and test.
Pipeline exists with zuul @ OSISM.

**Comment by garloff** [comment]
Avoid custom curl commands in a running container.
Better create an overlay container that contains the needed changes / modules / configuration.

**Comment by berendt** [comment]
E.g. https://github.com/osism/container-image-kolla-ansible/blob/main/.zuul.yaml#L28-L34

**Comment by berendt** [comment]
As discussed in SIG IAM we will prepare a SCS/container-images repository to be able to build nice overlay container images.

@garloff to create repo (add to github-manager), enable in zuul (@o-otte), add harbor robot secrets (think about namespaces: @garloff with @jschoone / dNation), @berendt to help with plugging, enabling renovate, @JuanPTM to create keycloak overlay there

**Comment by berendt** [comment]
PR for new repository is pending: https://github.com/SovereignCloudStack/github-manager/pull/162

**Comment by JuanPTM** [comment]
Closing this PR. Issue to create the new overlay container: https://github.com/SovereignCloudStack/issues/issues/453

**Pull request closed without merging**
