### PR TITLE
add repo_base

### PR DESCRIPTION
**Pull request by Richie1710**
Add the Path configurable with a repo_base for having Forks of testbed and terraform-base repos possible

### CODE REVIEW

**Review by osfrickler — COMMENTED** [review]
I don't understand how this is helping, now you'd need to override repo_base, but instead you could directly override basepath as well?

**Comment by artificial-intelligence** [comment]
I agree with @osfrickler's comment, but I think we could maybe move all these - same - `basepath` vars somewhere central, to avoid the current duplication.
The benefit would be that it can be changed in a central place.

This could possibly be extended to more variables.

What do you think?

**Comment by Richie1710** [comment]
Agree to @artificial-intelligence  . Any Idea where to place it ?

**Comment by berendt** [comment]
Replaced by https://github.com/osism/testbed/pull/1790

**Pull request closed without merging**
