### PR TITLE
Move tests from github actions to Zuul

### PR DESCRIPTION
**Pull request by osfrickler**
- Add doc8 and ansible-inventory to tox-linters job
- Fix inventory path for ansible-inventory check
- Remove github workflows for tests that are already running in Zuul
- Update terraform version in syntax check
- Fix some ansible-lint warnings
- Revert to using is_public attribute for image uploads
- Update .gitignore with further testing artifacts

Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>

### CODE REVIEW

**Comment by berendt** [comment]
Not related to the change itself. Double checked the URL. It is working...

```
2022-09-08 13:06:20.705672 | orchestrator | TASK [Download cirros image] ***************************************************
2022-09-08 13:06:20.705680 | orchestrator | Thursday 08 September 2022  13:06:09 +0000 (0:00:04.665)       0:00:49.684 ****
2022-09-08 13:06:20.705688 | orchestrator | fatal: [localhost]: FAILED! => {"changed": false, "dest": "/tmp/cirros.img", "elapsed": 10, "msg": "Request failed: <urlopen error _ssl.c:980: The handshake operation timed out>", "url": "https://github.com/cirros-dev/cirros/releases/download/0.5.2/cirros-0.5.2-x86_64-disk.img"}
```

**Comment by osfrickler** [comment]
recheck

**Comment by osfrickler** [comment]
We might want to add a retry to the downloads.

**Comment by berendt** [comment]
Yes, the retry makes sense. But then we can do it separately.

**Pull request merged**
