### PR TITLE
Bump default OpenStack version in terraform to yoga

### PR DESCRIPTION
**Pull request by osfrickler**
Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>

### CODE REVIEW

**Comment by osfrickler** [comment]
recheck

**Comment by berendt** [comment]
recheck

**Comment by osfrickler** [comment]
This patch still deploys xena in CI, needs more changes.

**Comment by berendt** [comment]
recheck

**Comment by osfrickler** [comment]
Hitting the real issue now in CI, at least one of them:

```
2022-09-05 22:06:26.729377 | orchestrator | fatal: [testbed-node-0.testbed.osism.xyz]: FAILED! => {"msg": "The conditional check 'inventory_hostname in groups[item.value.group]' failed. The error was: error while evaluating conditional (inventory_hostname in groups[item.value.group]): 'dict object' has no attribute 'ironic-tftp'\n\nThe error appears to be in '/ansible/roles/ironic/tasks/config.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Ensuring config directories exist\n  ^ here\n"}
```

Will update.

**Comment by berendt** [comment]
@osfrickler We should add a script that sync the inventory in cfg-generics with the upstream. This way it is probably easier to identify missing inventory groups.

**Comment by osfrickler** [comment]
recheck

**Review by berendt — APPROVED** [review]

**Review by ra-beer — APPROVED** [review]
LGTM

**Pull request merged**
