### PR TITLE
Add support for deploying OpenStack Zed

### PR DESCRIPTION
**Pull request by osfrickler**
Some changes in kolla need to be adapted to.

Use Ubuntu 22.04 as host image instead of 20.04.

Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>

### CODE REVIEW

**Comment by osfrickler** [comment]
recheck

**Comment by osfrickler** [comment]
recheck

**Comment by osfrickler** [comment]
recheck

**Comment by osfrickler** [comment]
recheck

**Comment by osfrickler** [comment]
recheck

**Comment by berendt** [comment]
Most of it I have built into individual PRs one by one.

**Comment by berendt** [comment]
All in. Defaults are changed separately. Ubuntu 22.04 as well.

**Pull request closed without merging**
